# Deployment for front-end
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: medicure
        image: chandan669/insurance:1.0
        ports:
        - containerPort: 8082
---
# Service for front-end with LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: insurance-deployment
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082  # match containerPort inside deployment